### PR TITLE
Issue#55 Add principal to Pac4jUser and add user to RoutingContext on…

### PR DESCRIPTION
**Pull request by HendrikLanghammer**
… authorize

The user has to be added to the RoutingContext, I'm not sure if I chose the best spot to do this.

Also returning null as vertx user principal is not too nice. I gave it a try with a very simple conversion to JsonObject, works fine for me.

### CODE REVIEW

**Comment by millross** [comment]
Thanks, I'll need to add an automated test or two based on your reproducer in the demo, but I think the problem you've identified is pretty much the one I suspected. I think there may be two places that need the fix (one for direct client login, one for indirect login so will think quite carefully about the fix).

**Comment by millross** [comment]
Hi Hendrik,

I've been unable to work on this over the weekend, so not progressed issue #55. What I can offer is to merge your PR in now (assuming it doesn't cause any existing tests to fail) but to leave the issue open so that I can revisit it with the additional testing/validation I want to ensure. What this means is that your fix will go in temporarily, but when I close issue #55 you might wish to re-test to ensure that I don't break any of your client code. If you'd prefer I can hold off altogether but it seems to me you might prefer to be able to use an up to date snapshot containing your PR as a temporary measure.

**Comment by HendrikLanghammer** [comment]
Hi Jez,
I go into winter holidays end of next week and actually would appreciate to switch back to pac4j:master before that. But I don't want to cause you any additional work, while nothing is happening on that branch I'm fine with my local fix. Thanks!

**Comment by millross** [comment]
That’s cool, I’ll try and get merged in this evening, though issue will remain open so I can do a more extensive review and fix later (I think there is more work to be done for completeness).

**Comment by millross** [comment]
This is merged, but issue will remain open pending review against the other considerations i recorded on it

**Pull request merged**
