### PR TITLE
Update Pac4jUser.java

### PR DESCRIPTION
**Pull request by gchegu**
while writing this object to byte, JSON object was stored to byte. But while reading same JSON object reading as UserProfile. I have applied the fix. Please review the fix

### CODE REVIEW

**Comment by millross** [comment]
Why do you feel the need to use the Java serialized version? The choice to use a JSON string was intentional. 

Please provide a failing test which clearly shows the problem, rather than just a set of changes. It seems that you want to replace use of json with a Java serialized object for use with clustered sessions, why do you consider this necessary?

**Comment by gchegu** [comment]
In this class, we can see two objects.
UserProfile userProfile;
JsonObject principal;

In cluster setup, both of these values need to be write into stream and read from stream.

While writing i can see as only principal object writing into buffer. But not userPofile object.

as only principal object written to buffer, While reading we can get only principal object not userPofile  object. But the reading method is reading the principal object as userPofile object and type casting to userPofile object

Due to this reason i was getting ClassCaseException. Sorry i dont have test case ready for this. I am justing pasting the exception i got.

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.pac4j.core.profile.UserProfile
        at org.pac4j.vertx.auth.Pac4jUser.readFromBuffer(Pac4jUser.java:85)
        at io.vertx.ext.web.handler.impl.UserHolder.readFromBuffer(UserHolder.java:76)
        ... 17 more

**Comment by millross** [comment]
Thanks. That's clearer, but I don't think your solution is the appropriate one. I'm pretty sure we can turn the json into a UserProfile directly (will check) rather than storing extra stuff into the buffer. I'll add a failing test at some point when I have time and turn it into an issue..

**Comment by millross** [comment]
Leaving this PR open till I have a test that replicates the issue and have converted it into an issue on Github.

**Comment by millross** [comment]
Note: this PR should NOT be merged as is, I believe there is a better solution.

**Comment by gchegu** [comment]
Yes, userprofile also can be converted into JSON. I was trying to reuse exist code of userprofile class.

**Comment by metryann** [comment]
Hello,
I have the same problem. I believe that we just need to pass JsonObject instead of String to the decodeObject method:

`final UserProfile userProfile = (UserProfile) DefaultJsonConverter.getInstance().decodeObject(**new JsonObject(json)**);`

**Comment by millross** [comment]
@metryann I think you're right, but I want to add a test to prevent regressions.

**Comment by millross** [comment]
Actually, I think the error is that I'm encoding principal when I should be encoding UserProfile. If you look, setUserProfile populates the principal from the user profile. Anyway, I'll fix by adding a test which should fail, then raise a Github issue.

**Comment by millross** [comment]
Added Issue #65 to track this so closing this PR.

**Pull request closed without merging**
